jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Install rbenv & ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init - bash)"' >> ~/.bashrc
          source ~/.bashrc
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      - name: Install Ruby 3.2.2
        run: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init - bash)"
          rbenv install 3.2.2
          rbenv global 3.2.2
          ruby -v

      - name: Install Bundler
        run: gem install bundler --user-install  # ✅ Correction ici

      - name: Install Jekyll Dependencies
        run: bundle install --path vendor/bundle

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "$BASE_PATH"
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path }}
          JEKYLL_ENV: production

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
